services:
  - type: web
    name: rudrayasa-direct-vn
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: APP_USER
        value: rudrayasa
      - key: APP_PASSWORD
        sync: false
      - key: SESSION_NAME
        value: rudrayasa-main
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: NODE_OPTIONS
        value: --max-old-space-size=192
